### ISSUE TITLE
Make `parse` and `syntax` take `Read`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/meta#260]
This will make it easier to use with binary data and files.
- [ ] `parse`
- [ ] `syntax`

**Comment by Binero** [comment]
`syntax` has same issue

**Comment by bvssvni** [comment]
`ParseError` would need to handle utf8 and io errors.

**Comment by Binero** [comment]
Issue is that CharsError can be any Error, and Error doesn't implement PartialEq. Because of this, and the way the library is built to return a `Result<_, (_, ParserError)>`, we wouldn't be able to assert_eq on what the parser returns.

**Comment by bvssvni** [comment]
Can we implement `PartialEq` for `ParseError`?

**Comment by Binero** [comment]
Not when it contains a CharsError.

**Comment by bvssvni** [comment]
One problem is that because the rules can backtrack when they fail, it might require the whole source in memory when parsing.

**Comment by bvssvni** [comment]
Won't implement this because of backtracking. Closing.
