### ISSUE TITLE
Switch from `Rc<String>` to `Arc<String>`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/meta#274]
This will make the meta data possible to move to another thread.

**Comment by bvssvni** [comment]
Using `Arc<String>` might require allocation to be shared across threads.

**Comment by Binero** [comment]
When creating a new `Arc` around a `String` (or any kind of heap data), the heap data does not get copied. It will allocate, but only the pointer.

**Comment by bvssvni** [comment]
The motivation to switch to `Arc<String>` is to reduce the overhead when converting to the `Table` structure from the table library.

**Comment by bvssvni** [comment]
This is needed for https://github.com/PistonDevelopers/eco/issues/68

**Comment by bvssvni** [comment]
Requires `Rule` to be `Sync`.
