### ISSUE TITLE
Can't figure out how to generate a JSON list

### ISSUE THREAD

**Issue by epurdy** [PistonDevelopers/meta#324]
Not sure if this is a documentation issue (i.e., I'm just not seeing the way to do it) or a missing feature.

**Comment by bvssvni** [comment]
https://docs.rs/piston_meta/0.29.1/piston_meta/json/fn.print.html

**Comment by epurdy** [comment]
Oh sorry, that wasn't very clear. I can't figure out how to do it through the Piston Meta syntax. I ended up having to generate a lisp-style list.

**Comment by bvssvni** [comment]
Closing.
